name: CI · Executar Testes Automatizados

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configura Node.js
        uses: actions/setup-node@v4
      
      - name: Instalar dependências
        run: |
          cd trabalho
          npm install

      - name: Executar testes
        run: |
          cd trabalho
          npx mocha trabalho-final.js --reporter tap
