name: CI · Executar Testes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Verifica código
        uses: actions/checkout@v3

      - name: Configura Node.js (v18)
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Instala dependências
        run: npm install

      - name: Executa testes
        run: npm test
